apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-chart.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "base-chart.fullname" . }}-frontend